import type { ElectoralLevel } from "./vote-intention";

export type TerritorialSignal = {
  title: string;
  summary: string;
  highlights?: string[];
  disclaimer: string;
  occurredAt: string;
  sourceName: string;
  sourceHref: string;
  /** Estas señales nunca se usan para ordenar listas ni como intención de voto. */
  verification: "verificada" | "en_revision" | "orientativa";
  /** Etiqueta específica cuando la limitación no es la falta de ficha técnica. */
  verificationLabel?: string;
  territory: {
    level: ElectoralLevel;
    departmentCode: string;
    provinceCode?: string;
    districtCode?: string;
  };
};

// Los reportes se muestran aparte de las mediciones verificadas. No se usan
// para calcular intención de voto, ordenar listas ni elaborar rankings.
export const territorialSignals: TerritorialSignal[] = [
  {
    title: "Sondeo parcial Vox Populi · cinco provincias",
    summary: "Preferencias para la gobernación regional medidas en Cajamarca, Jaén, Chota, San Ignacio y Santa Cruz; no cubre las 13 provincias de la región.",
    highlights: ["Felícita Tocto · 16.5 %", "Joaquín Ramírez · 16.0 %", "Edison Carrasco · 10.0 %", "Moisés Gonzales · 9.0 %", "NS/NO · 33.5 %"],
    disclaimer: "Estudio con ficha técnica y REE N.° 000512-JNE, pero de cobertura regional parcial. No representa al total de Cajamarca, no ordena listas regionales y la diferencia de 0.5 puntos entre los dos primeros está dentro del margen de error declarado (±2.95 %).",
    occurredAt: "2026-08-09",
    sourceName: "Vox Populi · ficha técnica REE",
    sourceHref: "https://www.voxpopuliperu.com/pdf/FT-%20CAJAMARCA%20AGOSTO%202026%20VOX%20POPULI.pdf",
    verification: "orientativa",
    verificationLabel: "Orientativa · cobertura parcial",
    territory: { level: "4", departmentCode: "06" },
  },
  {
    title: "Estudio de Vox Populi (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Provincial de Cajamarca.",
    highlights: ["Osías Ramírez · 12.0 %", "Edinson Terán · 11.0 %", "Sergio Sánchez · 10.5 %"],
    disclaimer: "Información orientativa (Nivel 2). Triple empate técnico en el liderato.",
    occurredAt: "2026-08-09",
    sourceName: "Vox Populi / La República",
    sourceHref: "https://www.voxpopuliperu.com/",
    verification: "orientativa",
    territory: { level: "5", departmentCode: "06", provinceCode: "01" },
  },
  {
    title: "Estudio de Vox Populi (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Provincial de Jaén.",
    highlights: ["Cleyver Aguilar · 24.5 %", "Fernando Zumarán · 12.5 %", "Rony Laban · 10.5 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-08-09",
    sourceName: "Vox Populi / La República",
    sourceHref: "https://www.voxpopuliperu.com/",
    verification: "orientativa",
    territory: { level: "5", departmentCode: "06", provinceCode: "08" },
  },
  {
    title: "Estudio de Vox Populi (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Provincial de Chota.",
    highlights: ["Neptalí Ticlla · 13.0 %", "Elder Fernandez · 12.0 %", "Wilfredo Colunche · 10.5 %"],
    disclaimer: "Información orientativa (Nivel 2). Empate técnico.",
    occurredAt: "2026-08-09",
    sourceName: "Vox Populi / La República",
    sourceHref: "https://www.voxpopuliperu.com/",
    verification: "orientativa",
    territory: { level: "5", departmentCode: "06", provinceCode: "06" },
  },
  {
    title: "Estudio de Vox Populi (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Provincial de Santa Cruz.",
    highlights: ["Marino Díaz · 15.5 %", "Pepe Alarcón · 14.0 %", "Luis Monteza · 8.0 %"],
    disclaimer: "Información orientativa (Nivel 2). Alto nivel de indecisión.",
    occurredAt: "2026-08-09",
    sourceName: "Vox Populi / La República",
    sourceHref: "https://www.voxpopuliperu.com/",
    verification: "orientativa",
    territory: { level: "5", departmentCode: "06", provinceCode: "09" },
  },
  {
    title: "Estudio de CIT Opinión & Mercado (Nivel 2)",
    summary: "Medición de preferencias para el Gobierno Regional de Loreto.",
    highlights: ["Fernando Meléndez · 23.3 %", "Jorge Mera · 11.2 %", "Vladimir Chong · 10.5 %", "Olmex Escalante · 10.3 %"],
    disclaimer: "Información orientativa (Nivel 2). Alto nivel de indecisión (32.5% entre Ninguno y NS/NO).",
    occurredAt: "2026-08-07",
    sourceName: "CIT Opinión & Mercado",
    sourceHref: "https://citopinion.pe/",
    verification: "orientativa",
    territory: { level: "4", departmentCode: "16" },
  },
  {
    title: "Estudio de Grupo Cusco (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Kosñipata (Paucartambo).",
    highlights: ["Juan José Rodriguez · 17.78 %", "Abraham Quispe · 17.22 %", "Carlos Acuña · 15.56 %", "Elvis Holgado · 9.44 %"],
    disclaimer: "Información orientativa (Nivel 2). Muestra escenario de empate técnico en el primer lugar.",
    occurredAt: "2026-08-09",
    sourceName: "Grupo Cusco Titular Provincias",
    sourceHref: "https://www.facebook.com/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "07", provinceCode: "11", districtCode: "05" },
  },
  {
    title: "Estudio de ICOP (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Provincial del Cusco.",
    highlights: ["William Peña · 12.6 %", "Albert Arenas · 12.5 %", "Sergio Sullca · 8.2 %", "Gabriela Paliza · 5.8 %"],
    disclaimer: "Información orientativa (Nivel 2). Alto nivel de NS/NO (41%).",
    occurredAt: "2026-08-15",
    sourceName: "ICOP",
    sourceHref: "https://www.facebook.com/",
    verification: "orientativa",
    territory: { level: "5", departmentCode: "07", provinceCode: "01" },
  },
  {
    title: "Sondeo de Qosqo Times (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Santiago (Cusco).",
    highlights: ["Lucho Villasante · 13.4 %", "Franklin Sotomayor · 11.4 %", "Fredy Vera · 10.5 %", "María Elena López · 3.9 %"],
    disclaimer: "Información orientativa (Nivel 2) publicada en prensa regional.",
    occurredAt: "2026-07-15",
    sourceName: "Qosqo Times",
    sourceHref: "https://qosqotimes.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "07", provinceCode: "01", districtCode: "06" },
  },
  {
    title: "Sondeo de IMOP (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Provincial de Trujillo.",
    highlights: ["Robert de la Cruz · 23.5 %", "Mario Reyna · 11.0 %", "Víctor León · 8.3 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-07-30",
    sourceName: "IMOP",
    sourceHref: "https://www.facebook.com/",
    verification: "orientativa",
    territory: { level: "5", departmentCode: "12", provinceCode: "01" },
  },
  {
    title: "Sondeo de CIT Opinión & Mercado (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de El Porvenir.",
    highlights: ["Junior Aguirre (Favorito en menciones)"],
    disclaimer: "Información orientativa (Nivel 2). Cifras porcentuales no publicadas.",
    occurredAt: "2026-06-15",
    sourceName: "CIT Opinión & Mercado",
    sourceHref: "https://citopinion.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "12", provinceCode: "01", districtCode: "10" },
  },
  {
    title: "Sondeo de CIT Opinión & Mercado (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Laredo.",
    highlights: ["Miguel Chávez (Favorito en menciones)"],
    disclaimer: "Información orientativa (Nivel 2). Cifras porcentuales no publicadas.",
    occurredAt: "2026-06-15",
    sourceName: "CIT Opinión & Mercado",
    sourceHref: "https://citopinion.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "12", provinceCode: "01", districtCode: "03" },
  },
  {
    title: "Sondeo de CIT Opinión & Mercado (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Víctor Larco Herrera.",
    highlights: ["Eduardo Muro (Favorito en menciones)"],
    disclaimer: "Información orientativa (Nivel 2). Cifras porcentuales no publicadas.",
    occurredAt: "2026-06-15",
    sourceName: "CIT Opinión & Mercado",
    sourceHref: "https://citopinion.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "12", provinceCode: "01", districtCode: "07" },
  },
  {
    title: "Sondeo de CIT Opinión & Mercado (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Salaverry.",
    highlights: ["Carmen Nunjar (Favorita en menciones)"],
    disclaimer: "Información orientativa (Nivel 2). Cifras porcentuales no publicadas.",
    occurredAt: "2026-06-15",
    sourceName: "CIT Opinión & Mercado",
    sourceHref: "https://citopinion.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "12", provinceCode: "01", districtCode: "05" },
  },
  {
    title: "Sondeo de CIT Opinión & Mercado (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Huanchaco.",
    highlights: ["José Ruíz (Favorito en menciones)"],
    disclaimer: "Información orientativa (Nivel 2). Cifras porcentuales no publicadas.",
    occurredAt: "2026-06-15",
    sourceName: "CIT Opinión & Mercado",
    sourceHref: "https://citopinion.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "12", provinceCode: "01", districtCode: "02" },
  },
  {
    title: "Sondeo de Sensor S.R.L. (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Carmen de la Legua-Reynoso.",
    highlights: ["Juan Gavilano · 16.0 %", "Daniel Lecca · 13.3 %", "Raúl Odar · 12.7 %", "Richard Tineo · 4.0 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-08-16",
    sourceName: "Sensor S.R.L.",
    sourceHref: "https://sensor.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "24", provinceCode: "01", districtCode: "04" },
  },
  {
    title: "Sondeo de Sensor S.R.L. (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de La Perla.",
    highlights: ["Pedro López · 25.3 %", "Giuliana Romero · 20.7 %", "Edgar Begazo · 12.0 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-08-16",
    sourceName: "Sensor S.R.L.",
    sourceHref: "https://sensor.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "24", provinceCode: "01", districtCode: "05" },
  },
  {
    title: "Sondeo de Imasolu (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Puente Piedra.",
    highlights: ["Rennán Espinoza Venegas · 37.43 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-08-14",
    sourceName: "Imasolu",
    sourceHref:
      "https://imasolu.com/portfolio/evaluacion-electoral-en-lima-metropolitana-julio-2026-candidatos-distritales-comienzan-a-definir-el-mapa-municipal-de-lima-metropolitana/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "19" },
  },
  {
    title: "Sondeo de Imasolu (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de San Luis.",
    highlights: ["Rosario López · 25.14 %", "Ricardo Castro · 8.57 %", "César Mendoza · 7.14 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-06-10",
    sourceName: "Imasolu",
    sourceHref:
      "https://imasolu.com/elecciones-lima-2026-asi-se-perfila-el-voto-en-san-luis-segun-el-estudio-evaluacion-electoral-en-lima-metropolitana-junio-2026/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "38" },
  },
  {
    title: "Sondeo de Imasolu (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Pachacámac.",
    highlights: ["Elvis Pómez · 58.29 %", "Héctor Quispe · 4.29 %", "Javier Ramírez Guerra · 3.14 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-08-14",
    sourceName: "Imasolu",
    sourceHref:
      "https://imasolu.com/portfolio/evaluacion-electoral-en-lima-metropolitana-julio-2026-candidatos-distritales-comienzan-a-definir-el-mapa-municipal-de-lima-metropolitana/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "16" },
  },
  {
    title: "Sondeo de IDICE del Perú (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Breña.",
    highlights: ["Ivan Chang · 12.0 %", "Isabel Rodriguez · 10.0 %", "Luis Ojeda · 8.0 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-06-20",
    sourceName: "IDICE del Perú",
    sourceHref: "https://idice.com.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "04" },
  },
  {
    title: "Sondeo de IDICE del Perú (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Lurín.",
    highlights: ["Juan Raúl Marticorena · 37.0 %", "Rosa Torrejón · 14.0 %", "Bernardo Silva · 13.0 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-08-10",
    sourceName: "IDICE del Perú",
    sourceHref: "https://idice.com.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "13" },
  },
  {
    title: "Sondeo de Imasolu (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Chaclacayo.",
    highlights: ["Marco Tello Castro · 30.5 %", "Iván Altamirano", "Jaime Callañaupa"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-06-15",
    sourceName: "Imasolu",
    sourceHref: "https://imasolu.com/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "07" },
  },
  {
    title: "Sondeo de Imasolu (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Villa El Salvador.",
    highlights: ["Kevin Íñigo · 40.29 %", "Homero Díaz · 3.14 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-06-15",
    sourceName: "Imasolu",
    sourceHref: "https://imasolu.com/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "41" },
  },
  {
    title: "Sondeo de Sensor S.R.L. (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Rímac.",
    highlights: ["Enrique Peramas · 25.3 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-06-15",
    sourceName: "Sensor S.R.L.",
    sourceHref: "https://sensor.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "22" },
  },
  {
    title: "Sondeo de Sensor S.R.L. (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de El Agustino.",
    highlights: ["Liborio Soria · 31.3 %", "Carmen Castillo · 7.3 %", "Cecilia Buleje · 6.3 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-06-15",
    sourceName: "Sensor S.R.L.",
    sourceHref: "https://sensor.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "35" },
  },
  {
    title: "Sondeo de IDICE del Perú (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Carabayllo.",
    highlights: ["Rosario Peláez · 22.0 %", "Nandy Córdova · 16.0 %", "Ladislao Espinoza · 14.0 %", "Wilmer Valverde · 13.0 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-08-05",
    sourceName: "IDICE del Perú",
    sourceHref: "https://idice.com.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "05" },
  },
  {
    title: "Sondeo de IDICE del Perú (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de La Victoria.",
    highlights: ["Alberto Moreno · 46.0 %", "Joe Zanabria · 13.0 %", "Susana Saldaña · 8.0 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-07-25",
    sourceName: "IDICE del Perú",
    sourceHref: "https://idice.com.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "09" },
  },
  {
    title: "Sondeo de Sensor S.R.L. (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de San Miguel.",
    highlights: ["Carolina Manucci · 17.0 %", "Marcos Cabrera · 16.3 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-08-16",
    sourceName: "Sensor S.R.L.",
    sourceHref: "https://sensor.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "27" },
  },
  {
    title: "Sondeo de IDICE del Perú (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Lince.",
    highlights: ["Luis Ernesto Flores · 26.0 %", "Jose Antonio Aliaga Pajares · 15.0 %", "Mirtha Uribe · 13.0 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-07-20",
    sourceName: "IDICE del Perú",
    sourceHref: "https://idice.com.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "11" },
  },
  {
    title: "Sondeo de CIT Opinión & Mercado (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Santa Anita.",
    highlights: ["Leonor Chumbimune · 27.6 %", "Cajo Huaringa · 27.6 %", "José Luis Nole Palomino · 22.0 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-08-15",
    sourceName: "CIT Opinión & Mercado",
    sourceHref: "https://citopinion.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "43" },
  },
  {
    title: "Sondeo de IDICE del Perú (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Chorrillos.",
    highlights: ["Henry Herrera Alemán · 22.0 %", "Augusto Miyashiro Y. · 21.0 %", "Ricardo Vásquez · 20.0 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-07-15",
    sourceName: "IDICE del Perú",
    sourceHref: "https://idice.com.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "08" },
  },
  {
    title: "Sondeo de Imasolu (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Independencia.",
    highlights: ["Gregorio Quispe · 14.5 %", "Alfredo Reynaga · 10.5 %", "Benigno Calderón · 7.4 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-06-15",
    sourceName: "Imasolu",
    sourceHref: "https://imasolu.com/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "34" },
  },
  {
    title: "Sondeo de Imasolu (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Surquillo.",
    highlights: ["Sandra Gutiérrez · 29.0 %", "José Luis Huamaní · 22.0 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-06-15",
    sourceName: "Imasolu",
    sourceHref: "https://imasolu.com/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "31" },
  },
  {
    title: "Sondeo de Sensor S.R.L. (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Barranco.",
    highlights: ["Antonio Mezarina · 21.3 %", "Manuel Espinoza · 15.7 %", "José Rodríguez · 7.7 %", "Angélica Noguerol · 5.3 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-08-15",
    sourceName: "Sensor S.R.L.",
    sourceHref: "https://sensor.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "25" },
  },
  {
    title: "Sondeo de Imasolu (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de Ate.",
    highlights: ["Manuel Vidal · 35.14 %", "Juan Enrique Dupuy", "Edde Cuellar"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-06-15",
    sourceName: "Imasolu",
    sourceHref: "https://imasolu.com/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "03" },
  },
  {
    title: "Sondeo de IDICE del Perú (Nivel 2)",
    summary: "Medición de preferencias para la Alcaldía Distrital de San Juan de Miraflores.",
    highlights: ["Dante Mendieta · 40.0 %", "Eloy Chávez · 13.0 %", "Karina Leandro · 10.0 %"],
    disclaimer: "Información orientativa (Nivel 2).",
    occurredAt: "2026-07-20",
    sourceName: "IDICE del Perú",
    sourceHref: "https://idice.com.pe/",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "14", provinceCode: "01", districtCode: "36" },
  },
  {
    title: "Sondeo local difundido por Diario Viral",
    summary:
      "Referencia publicada sobre la carrera por el Gobierno Regional de Arequipa.",
    highlights: [
      "Elmer Cáceres · 13.9 %",
      "Alfredo Zegarra · 11.6 %",
      "Berly Gonzáles · 11.1 %",
      "Jenry Huisa · 10.2 %",
    ],
    disclaimer:
      "Información orientativa: la ficha técnica completa no está accesible en una fuente pública verificable. No es una medición oficial.",
    occurredAt: "2026-07-23",
    sourceName: "Diario Viral",
    sourceHref:
      "https://diarioviral.pe/cercado/as-van-las-preferencias-para-elecciones-de-octubre-58639",
    verification: "orientativa",
    territory: { level: "4", departmentCode: "04" },
  },
  {
    title: "Sondeo local difundido por Diario Viral",
    summary:
      "Referencia publicada sobre la carrera por la Alcaldía Provincial de Arequipa.",
    highlights: [
      "Manuel Vera · 11.8 %",
      "Renzo Salas · 10.6 %",
      "Ricardo Ramírez · 8.3 %",
      "Sin decisión · 51.6 %",
    ],
    disclaimer:
      "Información orientativa: la ficha técnica completa no está accesible en una fuente pública verificable. No es una medición oficial.",
    occurredAt: "2026-07-23",
    sourceName: "Diario Viral",
    sourceHref:
      "https://diarioviral.pe/cercado/as-van-las-preferencias-para-elecciones-de-octubre-58639",
    verification: "orientativa",
    territory: { level: "5", departmentCode: "04", provinceCode: "01" },
  },
  {
    title: "Sondeo local difundido por Diario Viral",
    summary: "Sondeo de preferencias electorales para la Alcaldía Distrital de José Luis Bustamante y Rivero.",
    highlights: ["Jimmy Ojeda · 14.8 %"],
    disclaimer: "Información orientativa: la ficha técnica completa no está accesible en una fuente pública verificable. No es una medición oficial.",
    occurredAt: "2026-07-23",
    sourceName: "Diario Viral",
    sourceHref: "https://diarioviral.pe/cercado/as-van-las-preferencias-para-elecciones-de-octubre-58639",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "04", provinceCode: "01", districtCode: "29" },
  },
  {
    title: "Sondeo local difundido por Diario Viral",
    summary: "Sondeo de preferencias electorales para la Alcaldía Distrital de Mariano Melgar.",
    highlights: ["Carlos Andrade · 13.3 %"],
    disclaimer: "Información orientativa: la ficha técnica completa no está accesible en una fuente pública verificable. No es una medición oficial.",
    occurredAt: "2026-07-23",
    sourceName: "Diario Viral",
    sourceHref: "https://diarioviral.pe/cercado/as-van-las-preferencias-para-elecciones-de-octubre-58639",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "04", provinceCode: "01", districtCode: "26" },
  },
  {
    title: "Sondeo local difundido por Diario Viral",
    summary: "Sondeo de preferencias electorales para la Alcaldía Distrital de Cayma.",
    highlights: ["Jaime Chávez · 12.3 %"],
    disclaimer: "Información orientativa: la ficha técnica completa no está accesible en una fuente pública verificable. No es una medición oficial.",
    occurredAt: "2026-07-23",
    sourceName: "Diario Viral",
    sourceHref: "https://diarioviral.pe/cercado/as-van-las-preferencias-para-elecciones-de-octubre-58639",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "04", provinceCode: "01", districtCode: "02" },
  },
  {
    title: "Sondeo local difundido por Diario Viral",
    summary: "Sondeo de preferencias electorales para la Alcaldía Distrital de Paucarpata.",
    highlights: ["Justo Mayta · 12.6 %"],
    disclaimer: "Información orientativa: la ficha técnica completa no está accesible en una fuente pública verificable. No es una medición oficial.",
    occurredAt: "2026-07-23",
    sourceName: "Diario Viral",
    sourceHref: "https://diarioviral.pe/cercado/as-van-las-preferencias-para-elecciones-de-octubre-58639",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "04", provinceCode: "01", districtCode: "09" },
  },
  {
    title: "Sondeo local difundido por Diario Viral",
    summary: "Sondeo de preferencias electorales para la Alcaldía Distrital de Cerro Colorado.",
    highlights: ["Mirtha Ruelas · 11.3 %"],
    disclaimer: "Información orientativa: la ficha técnica completa no está accesible en una fuente pública verificable. No es una medición oficial.",
    occurredAt: "2026-07-23",
    sourceName: "Diario Viral",
    sourceHref: "https://diarioviral.pe/cercado/as-van-las-preferencias-para-elecciones-de-octubre-58639",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "04", provinceCode: "01", districtCode: "03" },
  },
  {
    title: "Sondeo referencial de Radio Yaraví",
    summary:
      "Sondeo referencial publicado para la elección del Gobierno Regional de Arequipa.",
    highlights: [
      "Elmer Cáceres · 5.51 %",
      "Alfredo Zegarra · 4.63 %",
      "Sin decisión · 68.28 %",
    ],
    disclaimer:
      "Radio Yaraví declara que el sondeo es referencial y sin sustento científico. No es una encuesta electoral oficial ni verificable.",
    occurredAt: "2026-08-24",
    sourceName: "Radio Yaraví",
    sourceHref:
      "https://radioyaravi.org.pe/noticia/el-poder-de-elegir/sondeo-referencial-mayoria-de-arequipenos-aun-no-define-por-quien-votar-para-gobernador-y-alcalde/",
    verification: "orientativa",
    territory: { level: "4", departmentCode: "04" },
  },
  {
    title: "Sondeo de opinión «Tacna Decide 2026»",
    summary:
      "Sondeo referencial publicado por BIGDATA Consultores y difundido en La República para el Gobierno Regional de Tacna.",
    highlights: [
      "Mario Ruiz · 35.01 %",
    ],
    disclaimer:
      "BIGDATA Consultores (REE 00433) difunde este estudio como sondeo. Su ficha técnica y metodología completa no son de acceso público, por lo que no es verificable ni constituye una medición oficial.",
    occurredAt: "2026-08-24",
    sourceName: "La República",
    sourceHref: "https://larepublica.pe",
    verification: "orientativa",
    territory: { level: "4", departmentCode: "22" },
  },
  {
    title: "Sondeo de opinión «Tacna Decide 2026»",
    summary:
      "Sondeo referencial publicado por BIGDATA Consultores para la Alcaldía Provincial de Tacna.",
    highlights: [
      "Niel Zavala · 33.75 %",
    ],
    disclaimer:
      "BIGDATA Consultores (REE 00433) difunde este estudio como sondeo. Su ficha técnica y metodología completa no son de acceso público, por lo que no es verificable ni constituye una medición oficial.",
    occurredAt: "2026-08-24",
    sourceName: "La República",
    sourceHref: "https://larepublica.pe",
    verification: "orientativa",
    territory: { level: "5", departmentCode: "22", provinceCode: "01" },
  },
  {
    title: "Sondeo de opinión «Tacna Decide 2026»",
    summary:
      "Sondeo referencial publicado por BIGDATA Consultores para la Alcaldía Distrital de Gregorio Albarracín.",
    highlights: [
      "Yoni Mamani Quispe · 27.31 %",
    ],
    disclaimer:
      "BIGDATA Consultores difunde este estudio como sondeo de opinión referencial y no oficial.",
    occurredAt: "2026-08-24",
    sourceName: "La República",
    sourceHref: "https://larepublica.pe",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "22", provinceCode: "01", districtCode: "13" },
  },
  {
    title: "Sondeo de opinión «Tacna Decide 2026»",
    summary:
      "Sondeo referencial publicado por BIGDATA Consultores para la Alcaldía Distrital de Pocollay.",
    highlights: [
      "José Carranza Zavala · 28.19 %",
    ],
    disclaimer:
      "BIGDATA Consultores difunde este estudio como sondeo de opinión referencial y no oficial.",
    occurredAt: "2026-08-24",
    sourceName: "La República",
    sourceHref: "https://larepublica.pe",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "22", provinceCode: "01", districtCode: "09" },
  },
  {
    title: "Sondeo de opinión «Tacna Decide 2026»",
    summary:
      "Sondeo referencial publicado por BIGDATA Consultores para la Alcaldía Distrital de La Yarada Los Palos.",
    highlights: [
      "Wilfredo Flores Quispe · 35.01 %",
    ],
    disclaimer:
      "BIGDATA Consultores difunde este estudio como sondeo de opinión referencial y no oficial.",
    occurredAt: "2026-08-24",
    sourceName: "La República",
    sourceHref: "https://larepublica.pe",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "22", provinceCode: "01", districtCode: "14" },
  },
  {
    title: "Sondeo de opinión «Tacna Decide 2026»",
    summary:
      "Sondeo referencial publicado por BIGDATA Consultores para la Alcaldía Distrital de Ciudad Nueva.",
    highlights: [
      "Julio Cueva Quispe · 24.16 %",
    ],
    disclaimer:
      "BIGDATA Consultores difunde este estudio como sondeo de opinión referencial y no oficial.",
    occurredAt: "2026-08-24",
    sourceName: "La República",
    sourceHref: "https://larepublica.pe",
    verification: "orientativa",
    territory: { level: "6", departmentCode: "22", provinceCode: "01", districtCode: "12" },
  },
];

export function signalsForTerritory(
  territory: TerritorialSignal["territory"],
) {
  return territorialSignals
    .filter(
      (signal) =>
        signal.territory.level === territory.level &&
        signal.territory.departmentCode === territory.departmentCode &&
        signal.territory.provinceCode === territory.provinceCode &&
        signal.territory.districtCode === territory.districtCode,
    )
    .sort(
      (a, b) =>
        new Date(b.occurredAt).getTime() - new Date(a.occurredAt).getTime(),
    );
}
